Rails/Date:
  EnforcedStyle: strict

Rails/Delegate:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Rails/SaveBang:
  Enabled: true

Rails/TimeZone:
  EnforcedStyle: strict
