inherit_from:
  - .rubocop_bundler.yml
  - .rubocop_lint.yml
  - .rubocop_metrics.yml
  - .rubocop_performance.yml
  - .rubocop_rails.yml
  - .rubocop_security.yml
  - .rubocop_style.yml

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - '**/db/**/*'
    - '**/marx/**/*'
    - '**/vendor/**/*'

# Disable all cops by default
DisabledByDefault: true

Rails:
  Enabled: true
