inherit_from:
  - https://git.effilab-local.com/world/style-guide/raw/master/ruby/.rubocop_bundler.yml
  - https://git.effilab-local.com/world/style-guide/raw/master/ruby/.rubocop_lint.yml
  - https://git.effilab-local.com/world/style-guide/raw/master/ruby/.rubocop_metrics.yml
  - https://git.effilab-local.com/world/style-guide/raw/master/ruby/.rubocop_performance.yml
  - https://git.effilab-local.com/world/style-guide/raw/master/ruby/.rubocop_rails.yml
  - https://git.effilab-local.com/world/style-guide/raw/master/ruby/.rubocop_security.yml
  - https://git.effilab-local.com/world/style-guide/raw/master/ruby/.rubocop_style.yml

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - '**/db/**/*'
    - '**/marx/**/*'
    - '**/vendor/**/*'
  # Disable all cops by default
  DisabledByDefault: true

Rails:
  Enabled: true
