Performance/Casecmp:
  Severity: refactor

Performance/Count:
  Severity: refactor

Performance/Detect:
  Severity: refactor

Performance/DoubleStartEndWith:
  Severity: warning

Performance/EndWith:
  Severity: warning

Performance/FixedSize:
  Enabled: false

Performance/FlatMap:
  Severity: refactor

Performance/HashEachMethods:
  Severity: warning

Performance/RedundantMatch:
  Enabled: false

Performance/RegexpMatch:
  Enabled: false # Enable after upate to ruby 2.4
