Style/AccessModifierIndentation:
  Enabled: true
  EnforcedStyle: indent
  # By default, the indentation width from Style/IndentationWidth is used
  # But it can be overridden by setting this parameter
  IndentationWidth: ~

Style/AccessorMethodName:
  Enabled: true

Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias_method

Style/AlignArray:
  # needs autocorrection
  Enabled: true

Style/AlignHash:
  # needs autocorrection
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: always_inspect

Style/AlignParameters:
  Enabled: true
  EnforcedStyle: with_first_parameter

Style/AndOr:
  Enabled: true
  EnforcedStyle: always

Style/ArrayJoin:
  Enabled: true

Style/AsciiComments:
  Enabled: true

Style/AsciiIdentifiers:
  Enabled: true

Style/Attr:
  Enabled: true

Style/AutoResourceCleanup:
  Enabled: false

Style/BarePercentLiterals:
  Enabled: false

Style/BeginBlock:
  Enabled: true

Style/BlockComments:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true
  EnforcedStyle: braces_for_chaining

Style/BlockEndNewline:
  Enabled: true

Style/BracesAroundHashParameters:
  Enabled: true
  EnforcedStyle: context_dependent

Style/CaseEquality:
  Enabled: false

Style/CaseIndentation:
  Enabled: true
  EnforcedStyle: case
  IndentOneStep: false

Style/CharacterLiteral:
  Enabled: true

Style/ClassAndModuleCamelCase:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: nested

Style/ClassCheck:
  Enabled: false

Style/ClassMethods:
  Enabled: true

Style/ClassVars:
  Enabled: true

Style/ClosingParenthesisIndentation:
  Enabled: true

Style/CollectionMethods:
  Enabled: true
 # Mapping from undesired method to desired_method
 # e.g. to use `detect` over `find`:
 #
 # CollectionMethods:
 #   PreferredMethods:
 #     find: detect
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/ColonMethodCall:
  Enabled: true

Style/CommandLiteral:
  Enabled: true
  EnforcedStyle: mixed
  AllowInnerBackticks: true

Style/CommentAnnotation:
  Enabled: true
  Keywords:
    - 'TODO'
    - 'FIXME'
    - 'OPTIMIZE'
    - 'HACK'
    - 'REVIEW'

Style/CommentIndentation:
  Enabled: true

Style/ConditionalAssignment:
  Enabled: false

Style/ConstantName:
  Enabled: true

Style/Copyright:
  Enabled: false

Style/DefWithParentheses:
  Enabled: true

Style/Documentation:
  Enabled: true

Style/DocumentationMethod:
  Enabled: true
  RequireForNonPublicMethods: true

Style/DotPosition:
  Enabled: true
  EnforcedStyle: leading

Style/DoubleNegation:
  Enabled: true

Style/EachForSimpleLoop:
  Enabled: true

Style/EachWithObject:
  Enabled: true

Style/ElseAlignment:
  Enabled: true

Style/EmptyCaseCondition:
  Enabled: true

Style/EmptyElse:
  Enabled: true
  EnforcedStyle:	both

Style/EmptyLineBetweenDefs:
  Enabled: true
  # If true, this parameter means that single line method definitions don't
  # need an empty line between them.
  AllowAdjacentOneLineDefs: false

Style/EmptyLines:
  # 2 lines offset
  Enabled: true

Style/EmptyLinesAroundAccessModifier:
  Enabled: true

Style/EmptyLinesAroundBlockBody:
  Enabled: true
  EnforcedStyle: no_empty_lines

Style/EmptyLinesAroundClassBody:
  Enabled: true
  EnforcedStyle: no_empty_lines

Style/EmptyLinesAroundMethodBody:
  Enabled: true

Style/EmptyLinesAroundModuleBody:
  Enabled: true
  EnforcedStyle: no_empty_lines

Style/EmptyLiteral:
  Enabled: true

Style/EmptyMethod:
 Enabled: false
 EnforcedStyle: expanded

Style/Encoding:
  Enabled: false

Style/EndBlock:
  Enabled: true

Style/EndOfLine:
  Enabled: true

Style/EvenOdd:
  Enabled: true

Style/ExtraSpacing:
  Enabled: true
  AllowForAlignment: true
  ForceEqualSignAlignment: false

Style/FileName:
  Enabled: true
  # File names listed in AllCops:Include are excluded by default. Add extra
  # excludes here.
  Exclude: []
  # When true, requires that each source file should define a class or module
  # with a name which matches the file name (converted to ... case).
  # It further expects it to be nested inside modules which match the names
  # of subdirectories in its path.
  ExpectMatchingDefinition: false
  # If non-nil, expect all source file names to match the following regex.
  # Only the file name itself is matched, not the entire file path.
  # Use anchors as necessary if you want to match the entire name rather than
  # just a part of it.
  Regex: ~
  # With `IgnoreExecutableScripts` set to `true`, this cop does not
  # report offending filenames for executable scripts (i.e. source
  # files with a shebang in the first line).
  IgnoreExecutableScripts: true

Style/FirstArrayElementLineBreak:
  Enabled: false

Style/FirstHashElementLineBreak:
  Enabled: false

Style/FirstMethodArgumentLineBreak:
  Enabled: false

Style/FirstMethodParameterLineBreak:
  Enabled: false

Style/FirstParameterIndentation:
  Enabled: false

Style/FlipFlop:
  Enabled: true

Style/For:
  Enabled: true
  EnforcedStyle: each

Style/FormatString:
  Enabled: true
  EnforcedStyle: format

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/GlobalVars:
  Enabled: true
  AllowedVariables: [$quiet, $shutdown]

Style/GuardClause:
  Enabled: true
  MinBodyLength: 1

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19_no_mixed_keys
  # Force hashes that have a symbol value to use hash rockets
  UseHashRocketsWithSymbolValues: false
  # Do not suggest { a?: 1 } over { :a? => 1 } in ruby19 style
  PreferHashRocketsForNonAlnumEndingSymbols: false

Style/IdenticalConditionalBranches:
  Enabled: true

Style/IfInsideElse:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: true
  MaxLineLength: 120

Style/IfUnlessModifierOfIfUnless:
  Enabled: true

Style/IfWithSemicolon:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: true

Style/IndentArray:
  Enabled: true
  EnforcedStyle: special_inside_parentheses
  IndentationWidth: ~

Style/IndentAssignment:
  Enabled: false

Style/IndentHash:
  Enabled: true
  EnforcedStyle: special_inside_parentheses
  IndentationWidth: ~

Style/IndentationConsistency:
  Enabled: true
  EnforcedStyle: rails

Style/IndentationWidth:
  Enabled: true
  # Number of spaces for each indentation level
  Width: 2

Style/InfiniteLoop:
  Enabled: true

Style/InitialIndentation:
  Enabled: true

Style/InlineComment:
  Enabled: false

Style/Lambda:
  Enabled: true
  EnforcedStyle: literal

Style/LambdaCall:
  Enabled: true
  EnforcedStyle: call

Style/LeadingCommentSpace:
  Enabled: true

Style/LineEndConcatenation:
  Enabled: true

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: true

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/MethodMissing:
  Enabled: true

Style/MethodName:
  Enabled: true
  EnforcedStyle: snake_case

Style/MissingElse:
  Enabled: false

Style/ModuleFunction:
  Enabled: true

Style/MultilineArrayBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Style/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: new_line

Style/MultilineBlockChain:
  Enabled: true

Style/MultilineBlockLayout:
  Enabled: true

Style/MultilineHashBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Style/MultilineIfModifier:
  Enabled: true

Style/MultilineIfThen:
  Enabled: true

Style/MultilineMemoization:
  Enabled: false

Style/MultilineMethodCallBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Style/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: aligned

Style/MultilineMethodDefinitionBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Style/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: aligned

Style/MultilineTernaryOperator:
  Enabled: true

Style/MutableConstant:
  Enabled: true

Style/NegatedIf:
  Enabled: true

Style/NegatedWhile:
  Enabled: true

Style/NestedModifier:
  Enabled: true

Style/NestedParenthesizedCalls:
  Enabled: true

Style/NestedTernaryOperator:
  Enabled: true

Style/Next:
  Enabled: true
  EnforcedStyle: skip_modifier_ifs
  MinBodyLength: 3

Style/NilComparison:
  Enabled: true

Style/NonNilCheck:
  Enabled: true
  IncludeSemanticChanges: false

Style/Not:
  Enabled: true

Style/NumericLiteralPrefix:
  Enabled: true
  EnforcedOctalStyle: zero_with_o

Style/NumericLiterals:
  Enabled: true
  MinDigits: 5

Style/NumericPredicate:
  Enabled: true
  EnforcedStyle: predicate
  Exclude:
    - 'spec/**/*'

Style/OneLineConditional:
  Enabled: true

Style/OpMethod:
  Enabled: true

Style/OptionHash:
  Enabled: false

Style/OptionalArguments:
  Enabled: true

Style/ParallelAssignment:
  Enabled: true

Style/ParenthesesAroundCondition:
  Enabled: true
  AllowSafeAssignment: false

Style/PercentLiteralDelimiters:
  Enabled: true
  PreferredDelimiters:
    '%':  ()
    '%i': ()
    '%I': ()
    '%q': ()
    '%Q': ()
    '%r': ()
    '%s': ()
    '%w': ()
    '%W': ()
    '%x': ()

Style/PercentQLiterals:
  Enabled: true

Style/PerlBackrefs:
  Enabled: true

Style/PredicateName:
  Enabled: true
  # Predicate name prefixes.
  NamePrefix:
    - is_
    - has_
    - have_
  # Predicate name prefixes that should be removed.
  NamePrefixBlacklist:
    - is_
    - has_
    - have_
  # Predicate names which, despite having a blacklisted prefix, or no ?,
  # should still be accepted
  NameWhitelist:
    - is_a?
  # Exclude Rspec specs because there is a strong convetion to write spec
  # helpers in the form of `have_something` or `be_something`.
  Exclude:
    - 'spec/**/*'

Style/PreferredHashMethods:
  Enabled: true
  EnforcedStyle: short

Style/Proc:
  Enabled: true

Style/RaiseArgs:
  Enabled: true
  EnforcedStyle: exploded

Style/RedundantBegin:
  Enabled: true

Style/RedundantException:
  Enabled: true

Style/RedundantFreeze:
  Enabled: true

Style/RedundantParentheses:
  Enabled: true

Style/RedundantReturn:
  Enabled: true
  AllowMultipleReturnValues: false

Style/RedundantSelf:
  Enabled: true

Style/RegexpLiteral:
  Enabled: false

Style/RescueEnsureAlignment:
  Enabled: true

Style/RescueModifier:
  Enabled: true

Style/SafeNavigation:
  Enabled: true
  ConvertCodeThatCanStartToReturnNil: false

Style/SelfAssignment:
  Enabled: true

Style/Semicolon:
  Enabled: true
  # Allow ; to separate several expressions on the same line.
  AllowAsExpressionSeparator: false

Style/Send:
  Enabled: false

Style/SignalException:
  Enabled: true
  EnforcedStyle: only_raise

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SpaceAfterColon:
  Enabled: true

Style/SpaceAfterComma:
  Enabled: true

Style/SpaceAfterMethodName:
  Enabled: true

Style/SpaceAfterNot:
  Enabled: true

Style/SpaceAfterSemicolon:
  Enabled: true

Style/SpaceAroundBlockParameters:
  Enabled: true

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Style/SpaceAroundKeyword:
  Enabled: true

Style/SpaceAroundOperators:
  Enabled: true
  # When true, allows most uses of extra spacing if the intent is to align
  # with an operator on the previous or next line, not counting empty lines
  # or comment lines.
  AllowForAlignment: true

Style/SpaceBeforeBlockBraces:
  Enabled: true

Style/SpaceBeforeComma:
  Enabled: true

Style/SpaceBeforeComment:
  Enabled: true

Style/SpaceBeforeFirstArg:
  Enabled: true
  AllowForAlignment: true

Style/SpaceBeforeSemicolon:
  Enabled: true

Style/SpaceInLambdaLiteral:
  Enabled: true
  EnforcedStyle: require_no_space

Style/SpaceInsideArrayPercentLiteral:
  Enabled: true

Style/SpaceInsideBlockBraces:
  Enabled: true

Style/SpaceInsideBrackets:
  Enabled: true

Style/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space

Style/SpaceInsideParens:
  Enabled: true

Style/SpaceInsidePercentLiteralDelimiters:
  Enabled: true

Style/SpaceInsideRangeLiteral:
  Enabled: true

Style/SpaceInsideStringInterpolation:
  Enabled: true
  EnforcedStyle: no_space

Style/SpecialGlobalVars:
  Enabled: true
  EnforcedStyle: use_english_names

Style/StabbyLambdaParentheses:
  Enabled: true
  EnforcedStyle: require_parentheses

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: false

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringMethods:
  Enabled: true
  # Mapping from undesired method to desired_method
  # e.g. to use `to_sym` over `intern`:
  #
  # StringMethods:
  #   PreferredMethods:
  #     intern: to_sym
  PreferredMethods:
    intern: to_sym

Style/StructInheritance:
  Enabled: true

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: percent

Style/SymbolLiteral:
  Enabled: true

Style/SymbolProc:
  Enabled: true

Style/Tab:
  Enabled: true

Style/TernaryParentheses:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: true
  EnforcedStyle: final_newline

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingUnderscoreVariable:
  Enabled: true
  AllowNamedUnderscoreVariables: true

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/TrailingWhitespace:
  Enabled: true

Style/TrivialAccessors:
  Enabled: true
  # When set to false the cop will suggest the use of accessor methods
  # in situations like:
  #
  # def name
  #   @other_name
  # end
  #
  # This way you can uncover "hidden" attributes in your code.
  ExactNameMatch: true
  AllowPredicates: true
  # Allows trivial writers that don't end in an equal sign. e.g.
  #
  # def on_exception(action)
  #   @on_exception=action
  # end
  # on_exception :restart
  #
  # Commonly used in DSLs
  AllowDSLWriters: false
  IgnoreClassMethods: false
  Whitelist:
    - to_ary
    - to_a
    - to_c
    - to_enum
    - to_h
    - to_hash
    - to_i
    - to_int
    - to_io
    - to_open
    - to_path
    - to_proc
    - to_r
    - to_regexp
    - to_str
    - to_s
    - to_sym

Style/UnlessElse:
  Enabled: true

Style/UnneededCapitalW:
  Enabled: true

Style/UnneededInterpolation:
  Enabled: true

Style/UnneededPercentQ:
  Enabled: true

Style/VariableInterpolation:
  Enabled: true

Style/VariableName:
  Enabled: true
  EnforcedStyle: snake_case

Style/VariableNumber:
  Enabled: true
  EnforcedStyle: normalcase
  Exclude:
   - 'spec/**/*'
   - 'vendor/**/*'

Style/WhenThen:
  Enabled: true

Style/WhileUntilDo:
  Enabled: true

Style/WhileUntilModifier:
  Enabled: true
  MaxLineLength: 120

Style/WordArray:
  Enabled: true
  EnforcedStyle: percent
  SupportedStyles:
  # The MinSize option causes the WordArray rule to be ignored for arrays
  # smaller than a certain size.  The rule is only applied to arrays
  # whose element count is greater than or equal to MinSize.
  MinSize: 1

Style/ZeroLengthPredicate:
  Enabled: true
