Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/BarePercentLiterals:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/CaseEquality:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassCheck:
  Enabled: false

Style/CollectionMethods:
  Enabled: true

Style/CommandLiteral:
  EnforcedStyle: mixed
  AllowInnerBackticks: true

Style/ConditionalAssignment:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/EmptyMethod:
 Enabled: false

Style/Encoding:
  Enabled: false

Style/GlobalVars:
  AllowedVariables: [$quiet, $shutdown]

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/IfUnlessModifier:
  MaxLineLength: 120

Style/IfWithSemicolon:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: true

Style/Lambda:
  EnforcedStyle: literal

Style/MultilineMemoization:
  Enabled: false

Style/ParenthesesAroundCondition:
  AllowSafeAssignment: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '()'

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TernaryParentheses:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/WhileUntilModifier:
  MaxLineLength: 120

Style/WordArray:
  # The MinSize option causes the WordArray rule to be ignored for arrays
  # smaller than a certain size.  The rule is only applied to arrays
  # whose element count is greater than or equal to MinSize.
  MinSize: 1
