Lint/AssignmentInCondition:
  AllowSafeAssignment: false

Lint/NonLocalExitFromIterator:
  Enabled: false

Lint/UnusedBlockArgument:
  AllowUnusedKeywordArguments: true

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
